# Generated by Django 3.1.3 on 2020-12-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JKFPost',
            fields=[
                ('tid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('zone', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField(blank=True, max_length=50)),
                ('is_found', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
