# Generated by Django 4.0.5 on 2022-12-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_jkfpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='jkfpost',
            name='tag',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
