# Generated by Django 4.0.5 on 2022-12-30 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_jkfpost_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='jkfpost',
            name='status',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
