# Generated by Django 4.0.5 on 2022-12-30 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_jkfpost_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='JKFTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.IntegerField()),
                ('tag', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('zone', 'tag')},
            },
        ),
    ]
