# Generated by Django 4.0.5 on 2023-07-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_jkftag'),
    ]

    operations = [
        migrations.AddField(
            model_name='jkfpost',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
