# Generated by Django 4.2.6 on 2024-04-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_jkfpost_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="jkftag",
            name="name",
            field=models.CharField(default="", max_length=50),
        ),
    ]
